name: Notify Discord on Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  notify-discord:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          DESCRIPTION="${{ github.event.pull_request.body }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PREVIEW_URL="https://deploy-preview-${{ github.event.pull_request.number }}--mibodega-admin.netlify.app/"
          
          # Extraer los logins de los asignados
          ASSIGNEES=$(echo '${{ toJson(github.event.pull_request.assignees) }}' | jq -r 'map(.login) | join(", ")')
          
          # Validar si hay asignados
          if [ -z "$ASSIGNEES" ]; then
            ASSIGNEES="No hay personas asignadas"
          fi

          PAYLOAD=$(jq -n --arg url "$PR_URL" --arg preview "$PREVIEW_URL" --arg title "$TITLE" --arg description "$DESCRIPTION" --arg assignees "$ASSIGNEES" '{"content": "Nuevo pull request que necesita QA: \($url)\n\n**Vista previa:** \($preview)\n**Título:** \($title)\n\($description)\n**Asignados:** \($assignees)"}')
          echo "Payload: $PAYLOAD"
          curl -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
