name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  notify-discord:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Nuevo pull request que necesita QA: ${{ github.event.pull_request.html_url }}\"}" \
          $DISCORD_WEBHOOK_URL
