name: Notify Discord on Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  notify-discord:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get Pull Request Assignees
        id: get-assignees
        run: |
          ASSIGNEES_RAW=$(curl -s \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees")
          echo "Raw Assignees Data: $ASSIGNEES_RAW"
          ASSIGNEES=$(echo "$ASSIGNEES_RAW" | jq -r '.assignees[]?.login' | paste -sd ", ")
          echo "Assignees: $ASSIGNEES"
          echo "::set-output name=assignees::$ASSIGNEES"

      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          MENTION="<@788195198487363615>"
          TITLE="${{ github.event.pull_request.title }}"
          DESCRIPTION="${{ github.event.pull_request.body }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PREVIEW_URL="https://deploy-preview-${{ github.event.pull_request.number }}--mibodega-admin.netlify.app/"
          ASSIGNEES="${{ steps.get-assignees.outputs.assignees }}"
          PAYLOAD=$(jq -n --arg url "$PR_URL" --arg preview "$PREVIEW_URL" --arg mention "$MENTION" --arg title "$TITLE" --arg description "$DESCRIPTION" --arg assignees "$ASSIGNEES" '{"content": "Nuevo pull request que necesita QA: \($url)\n\n**Vista previa:** \($preview)\n**Título:** \($title)\n\($description)\n**Asignados:** \($assignees)\nMencionado: \($mention)"}')
          curl -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
